sudo: false
language: node_js
node_js:
  - "node"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - npm update
install:
  - npm install
script:
  - npm run prepublish
deploy:
  - provider: npm
    email: max@rururu.me
    api_key: ${NPM_TOKEN}
    on:
      branch: master
