sudo: false
language: node_js
node_js:
- node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm run build
deploy:
- provider: npm
  email: $NPM_USER
  skip_cleanup: true
  on:
    branch: master
  api_key: $NPM_TOKEN
